
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from tkinter import ttk


# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox
import subprocess


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\GYM-PROGRAM\GymTrack\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

# Function to validate the login
def validate_login():
    userid = entry_1.get()
    password = entry_2.get()

    # You can add your own validation logic here
    if userid == "admin" and password == "admin":
    
        messagebox.showinfo("Login Successful", "Welcome, Admin!")
        window.destroy()  

        subprocess.run(['python', 'gymLogs.py'])
    else:
        messagebox.showerror("Login Failed", "Invalid username or password")

window = Tk()

window.geometry("900x700")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 700,
    width = 900,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    450.0,
    41.0,
    image=image_image_1
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    449.0,
    410.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#E4E4E4",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=322.0,
    y=393.0,
    width=254.0,
    height=33.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    452.0,
    493.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#E4E4E4",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=325.0,
    y=476.0,
    width=254.0,
    height=33.0,
)

entry_2.config(show="*")

canvas.create_text(
    29.0,
    30.0,
    anchor="nw",
    text="GymTrack",
    fill="#FFFFFF",
    font=("Inter Bold", 18 * -1)
)

canvas.create_text(
    416.0,
    326.0,
    anchor="nw",
    text="Login ",
    fill="#000000",
    font=("Inter Bold", 24 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=validate_login,
    relief="flat"
)
button_1.place(
    x=325.0880126953125,
    y=544.415283203125,
    width=253.05484008789062,
    height=45.58473205566406
)

canvas.create_text(
    322.0,
    368.0,
    anchor="nw",
    text="Username:",
    fill="#474747",
    font=("Inter Bold", 14 * -1)
)

canvas.create_text(
    325.0,
    450.0,
    anchor="nw",
    text="Password:",
    fill="#474747",
    font=("Inter Bold", 14 * -1)
)


image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    446.0,
    222.0,
    image=image_image_2
)


image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    857.0,
    41.0,
    image=image_image_3
)
window.resizable(False, False)
window.mainloop()
